// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIcjrSwccXPB2U65NNNyHjFu4_S4dX1Vc',
    appId: '1:662824272658:web:2b0dbc0c1afe4fb74da9cb',
    messagingSenderId: '662824272658',
    projectId: 'neu-001563042',
    authDomain: 'neu-001563042.firebaseapp.com',
    storageBucket: 'neu-001563042.appspot.com',
    measurementId: 'G-YR8H867KQY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAntND9Vxzzim4CBQf4GEv4_UoSEztsYhs',
    appId: '1:662824272658:android:4881c57ffef7d2504da9cb',
    messagingSenderId: '662824272658',
    projectId: 'neu-001563042',
    storageBucket: 'neu-001563042.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5CX2xC3K0Mmdq37KdnrHM3d3v-izEnHY',
    appId: '1:662824272658:ios:1d7ea139a276bcff4da9cb',
    messagingSenderId: '662824272658',
    projectId: 'neu-001563042',
    storageBucket: 'neu-001563042.appspot.com',
    androidClientId: '662824272658-1ob2vkljlslsdfkvu2j1prin89k9lq3r.apps.googleusercontent.com',
    iosClientId: '662824272658-pvt649r765gfpu50u25oj4olk2gjajto.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5CX2xC3K0Mmdq37KdnrHM3d3v-izEnHY',
    appId: '1:662824272658:ios:1d7ea139a276bcff4da9cb',
    messagingSenderId: '662824272658',
    projectId: 'neu-001563042',
    storageBucket: 'neu-001563042.appspot.com',
    androidClientId: '662824272658-1ob2vkljlslsdfkvu2j1prin89k9lq3r.apps.googleusercontent.com',
    iosClientId: '662824272658-pvt649r765gfpu50u25oj4olk2gjajto.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplicationFinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIcjrSwccXPB2U65NNNyHjFu4_S4dX1Vc',
    appId: '1:662824272658:web:3e8fe13bd6fdd9b24da9cb',
    messagingSenderId: '662824272658',
    projectId: 'neu-001563042',
    authDomain: 'neu-001563042.firebaseapp.com',
    storageBucket: 'neu-001563042.appspot.com',
    measurementId: 'G-1P8XVN5VXZ',
  );

}